[project]
name = "paperless-quadlet"
version = "0.1.0"
description = ""
authors = [
    { name = "Gregor A. Segner", email = "gregor.segner@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.0"
dependencies= [
    "pypyr>=5.9.1",
    "jinja2-cli>=0.8.2"
]