name: Bug Report
description: Submit a bug
title: "[BUG]: "
labels: [ "bug" ]
body:
- type: markdown
  attributes:
    value: |
      Thaks for submitting a bug!
- type: dropdown
  id: deploytype
  attributes:
    label: Method
    description: Which deploy method do you use
    options:
    - standalone with script (default)
    - ansible + quadlets
    default: 0
- type: textarea
  id: os-info
  attributes:
    label: os-info
    description: Plese proide information about your OS/distribution
    value: "your os information goes here"
    validations:
      required: true
- type: textarea
  id: pod-info
  attributes:
    label: pod-info
    description: Please provide your podman version
    value: "your podman information goes here"
    validations:
      required: true
- type: textarea
  id: report
  attributes:
    label: report
    description: plese describe the problem, also include your expectations
    value: "your bug report goes here"
    validations:
      required: true
